from Tests.example_COTP import example_COTP
from Tests.example_S7CommJobReadVar import example_S7CommJobReadVar
from Tests.example_S7commAckDataReadVar import example_S7commAckDataReadVar
from Tests.example_S7CommSetup import example_S7CommSetup